{
 "title": "Jenkins: Performance and Health Overview",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "2024-12-11T17:30:21.613Z", "to": "2024-12-11T17:38:30.137Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processing speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jenkins_job_queuing_duration" }
   ]
  },
  {
   "title": "Queued rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1m])"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{instance=\"jenkins.jenkins.svc.cluster.local:8080\"}"
    }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_offline_value" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_cpu_load" }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_builds_count" }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "Aborted Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_aborted_total" }
   ]
  },
  {
   "title": "Unstable Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_unstable_total" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Executor free",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Executors health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(sum(jenkins_job_building_duration)/sum(jenkins_job_building_duration_count))"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  { "title": "Plugins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Plugins active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_active" }
   ]
  },
  {
   "title": "Plugins with pending updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_withUpdate" }
   ]
  },
  {
   "title": "Plugins inactive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive" }
   ]
  },
  {
   "title": "Plugins failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_failed" }
   ]
  },
  { "title": "Health check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Health check duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "jenkins_health_check_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{instance=~\"jenkins.jenkins.svc.cluster.local:8080\"}/1000/60/60/24"
    }
   ]
  },
  {
   "title": "Health check count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_health_check_count" }
   ]
  },
  {
   "title": "Health check score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  }
 ]
}